# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-12 20:12
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('stature', models.CharField(blank=True, max_length=6)),
                ('usual_host', models.CharField(blank=True, max_length=128, null=True)),
            ],
            options={
                'verbose_name_plural': 'people',
            },
        ),
        migrations.CreateModel(
            name='WeightEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('weight', models.FloatField()),
                ('trend', models.FloatField()),
                ('who', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diet.Person')),
            ],
            options={
                'verbose_name_plural': 'weight entries',
            },
        ),
    ]
